# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

add_newline = true
scan_timeout = 100
command_timeout = 1000
continuation_prompt = '[∙](cyan) '

[cmd_duration]
show_milliseconds = true

[username]
disabled = false
style_user = 'blue bold'
style_root = 'purple bold'
show_always = true

[git_status]
ahead = '⇡${count}'
diverged = '⇕⇡${ahead_count}⇣${behind_count}'
behind = '⇣${count}'

[time]
use_12hr = true
disabled = false

